import {mkdir,readFile,writeFile,readdir} from 'node:fs/promises';
const root=new URL('./',import.meta.url);
const source=await readFile(new URL('server.mjs',root),'utf8');
const api=source.slice(source.indexOf('const cache='),source.indexOf('const publicFiles=' )).replace('export async function city(area)','async function city(area,apiKey)').replaceAll('process.env.SEOUL_API_KEY','apiKey').replaceAll('export ','');
const areas=(await readFile(new URL('public/areas.js',root),'utf8')).replaceAll('export ','');
const assets={};
for(const name of await readdir(new URL('public/',root))){if(/\.(js|css|html)$/.test(name))assets['/'+name]=await readFile(new URL('public/'+name,root),'utf8');}
assets['/']=assets['/index.html'];
const binaryAssets={};
for(const name of await readdir(new URL('public/downloads/',root))){if(/\.(pdf|xlsx)$/.test(name))binaryAssets['/downloads/'+name]=(await readFile(new URL('public/downloads/'+name,root))).toString('base64');}
const handler=`\nimport {cloudStore} from './cloud-store.js';\nconst assets=${JSON.stringify(assets)};\nconst binaryAssets=${JSON.stringify(binaryAssets)};\nexport default {async fetch(request,env){const url=new URL(request.url);const headers={'X-Content-Type-Options':'nosniff','Cache-Control':'no-store','Referrer-Policy':'no-referrer'};const send=(status,data,type='application/json; charset=utf-8')=>new Response(type.startsWith('application/json')?JSON.stringify(data):data,{status,headers:{...headers,'Content-Type':type}});if(url.pathname==='/api/projects')return cloudStore(request,env);if(request.method!=='GET')return send(405,{error:'지원하지 않는 요청입니다.'});if(url.pathname==='/api/status')return send(200,{seoulConfigured:!!env.SEOUL_API_KEY,areas:Object.keys(areas),weather:'Open-Meteo',storage:'browser'});if(['/api/city','/api/weather'].includes(url.pathname)){const area=url.searchParams.get('area');if(!Object.hasOwn(areas,area))return send(400,{state:'error',message:'지원 지역을 선택해 주세요.'});try{return send(200,await(url.pathname==='/api/city'?city(area,env.SEOUL_API_KEY):weather(area)));}catch{return send(502,{state:'error',message:'외부 데이터 조회에 실패했습니다. 연결과 제공처 상태를 확인해 주세요.'});}}if(Object.hasOwn(binaryAssets,url.pathname)){const bytes=Uint8Array.from(atob(binaryAssets[url.pathname]),c=>c.charCodeAt(0)),name=url.pathname.split('/').at(-1),type=url.pathname.endsWith('.pdf')?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';return new Response(bytes,{status:200,headers:{...headers,'Content-Type':type,'Content-Disposition':'attachment; filename="'+name+'"'}});}if(!Object.hasOwn(assets,url.pathname))return send(404,{error:'페이지가 없습니다.'});return send(200,assets[url.pathname],url.pathname.endsWith('.js')?'text/javascript; charset=utf-8':url.pathname.endsWith('.css')?'text/css; charset=utf-8':'text/html; charset=utf-8');}};`;
await mkdir(new URL('dist/server/',root),{recursive:true});await writeFile(new URL('dist/server/index.js',root),areas+'\n'+api+handler);
await mkdir(new URL('dist/.openai/',root),{recursive:true});await writeFile(new URL('dist/.openai/hosting.json',root),await readFile(new URL('.openai/hosting.json',root)));
await writeFile(new URL('dist/server/cloud-store.js',root),(await readFile(new URL('cloud-store.js',root),'utf8')).replace("'./public/core.js'","'./core.js'"));
for(const name of await readdir(new URL('public/',root))){if(name.endsWith('.js'))await writeFile(new URL('dist/server/'+name,root),await readFile(new URL('public/'+name,root)));}
console.log('Worker built with public assets and server-only API key binding.');
