import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {cloudStore} from '../cloud-store.js';
import {initial} from '../public/core.js';
import {upgrade} from '../public/care.js';
test('모든 브라우저 모듈 문법 검사',()=>{for(const name of readdirSync(new URL('../public/',import.meta.url)).filter(n=>n.endsWith('.js')))execFileSync(process.execPath,['--check',new URL('../public/'+name,import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')]);});
test('사이트 저장, 조회, 충돌 방지, 요청 출처 검사',async()=>{const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../drizzle/0000_neat_hiroim.sql',import.meta.url),'utf8'));
 const env={DB:{prepare(query){let args=[];const s=sql.prepare(query);return{bind(...a){args=a;return this;},async all(){return{results:s.all(...args)};},async first(){return s.get(...args);},async run(){return {meta:{changes:s.run(...args).changes}};}};}}};
 const p=upgrade(initial(false)),put=(revision,origin='https://event.test')=>new Request('https://event.test/api/projects',{method:'PUT',headers:{Origin:origin,'X-Event-Save':'1'},body:JSON.stringify({project:p,revision})});
 assert.equal((await cloudStore(put(0),env)).status,200);
 assert.equal((await cloudStore(put(0),env)).status,409);
 assert.equal((await cloudStore(put(1,'https://wrong.test'),env)).status,403);
 assert.equal((await cloudStore(put(1),env)).status,200);
 const result=await (await cloudStore(new Request('https://event.test/api/projects?id='+p.id),env)).json();assert.equal(result.revision,2);assert.equal(result.project.id,p.id);
 const list=await (await cloudStore(new Request('https://event.test/api/projects'),env)).json();assert.equal(list.projects.length,1);
 assert.equal((await cloudStore(put(2),{})).status,503);sql.close();
});
