import test from 'node:test';
import assert from 'node:assert/strict';
import {initial,validate,report} from '../public/core.js';
import {upgrade} from '../public/care.js';
import {createCase,advanceCase,caseState,casesToBatch,journeyReady} from '../public/journey.js';
import {memberSummary} from '../public/membership.js';
const now='2026-10-06T03:00:00.000Z';
function fixture(){const p=upgrade(initial());p.sector='패션, 아이웨어';p.recommended=p.venues[0].id;Object.assign(p.journey,{title:'가상 체험',brief:'가상 안내',doneRule:'가상 완료 조건',nextAction:'관리 가이드',nextHelp:'가상 후속 내용',days:7});p.membership.program='가상 회원';p.membership.benefit='가상 혜택';return p;}
test('전체 여정은 장소, 체험, 혜택, 후속 조건을 요구한다',()=>{const p=fixture();assert.ok(journeyReady(p).every(x=>x.ok));p.journey.nextAction='';assert.throws(()=>createCase(p,now));p.journey.nextAction='가이드';p.venues[0].conditions[0]='미충족';assert.throws(()=>createCase(p,now));});
test('방문→체험→혜택→가입→후속을 순서대로 기록하고 중복을 막는다',()=>{const p=fixture(),c=createCase(p,now);p.journey.cases.push(c);assert.throws(()=>advanceCase(c,'enroll',now));for(const t of ['experience','offer','enroll','followup'])advanceCase(c,t,now);assert.equal(c.events.length,5);assert.equal(caseState(c).used,true);assert.match(caseState(c).memberCode,/CASE-/);assert.equal(c.events.at(-1).at,'2026-10-13T03:00:00.000Z');assert.equal(c.events.at(-1).recordedAt,now);assert.throws(()=>advanceCase(c,'followup',now));validate(p);});
test('가입 거절은 체험을 유지하고 회원, 후속 이용을 만들지 않는다',()=>{const p=fixture(),c=createCase(p,now);p.journey.cases.push(c);for(const t of ['experience','offer','decline'])advanceCase(c,t,now);assert.equal(caseState(c).experienced,true);assert.equal(caseState(c).enrolled,false);assert.throws(()=>advanceCase(c,'enroll',now));assert.throws(()=>advanceCase(c,'followup',now));validate(p);});
test('소식 수신 거절 상태에서도 체험용 회원 생성이 가능하다',()=>{const c=createCase(fixture(),now);for(const t of ['experience','offer','enroll'])advanceCase(c,t,now);assert.equal(c.choice,'받지 않음');assert.equal(caseState(c).enrolled,true);});
test('조건이 달라지면 이전 모의 운영을 보존하고 서로 다른 집단을 합치지 않는다',()=>{const p=fixture(),a=createCase(p,now);p.journey.cases.push(a);p.journey.title='변경된 체험';p.journey.cases.push(createCase(p,now));assert.equal(a.setup.title,'가상 체험');assert.equal(casesToBatch(p,a.id).total,1);});
test('완료와 거절 경로를 가상 집계로 내보내고 사용자 입력을 보존한다',()=>{const p=fixture();for(const end of ['followup','decline']){const c=createCase(p,now);p.journey.cases.push(c);for(const t of (end==='followup'?['experience','offer','enroll','followup']:['experience','offer','decline']))advanceCase(c,t,now);}const b=casesToBatch(p,p.journey.cases[0].id);assert.deepEqual(b.counts,[2,2,1,1,1]);assert.equal(b.kind,'가상 연습');assert.equal(memberSummary(b).conversion,50);p.membership.batches.push(b);const q=validate(JSON.parse(JSON.stringify(p)));assert.equal(q.journey.cases.length,2);assert.match(report(q),/가입 없이 종료/);assert.match(report(q),/실제 회원 생성/);});
test('백업의 순서 위조, 중복 이벤트, 후속 시각 오류를 거부한다',()=>{const p=fixture(),c=createCase(p,now);p.journey.cases.push(c);c.events.push({type:'followup',at:now,recordedAt:now});assert.throws(()=>validate(p));c.events.pop();for(const t of ['experience','offer','enroll','followup'])advanceCase(c,t,now);c.events.at(-1).at=now;assert.throws(()=>validate(p));});
test('작성 중 비운 후속 일수는 초안에 보존하지만 모의 운영 시작은 막는다',()=>{const p=fixture();p.journey.days=null;assert.equal(validate(p).journey.days,null);assert.throws(()=>createCase(p,now));});
